config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'statics#top'

  resource :account_settings, only: %i[show] do
    scope module: 'account_settings' do
      resource :article_notification_conditions, only: %i[edit update]
      resource :emails, only: %i[edit update]
      resource :passwords, only: %i[edit update]
      resource :profiles, only: %i[edit update]
      resource :privacies, only: %i[edit update]
      resource :notifications, only: %i[edit update]
    end
  end
  resources :articles
  resources :helps, only: %i[index]
  resources :improvement_requests, only: %i[new create]
  resources :inquiries, only: %i[new create]
  resources :privacy_policies, only: %i[index]
  resources :statics, only: %i[] do
    collection do
      get :top
    end
  end
  resources :terms, only: %i[index]
  resources :users, only: %i[index] do
    scope module: 'users' do
      get '/', to: 'profiles#show'
      resource :profile, only: %i[show]
      resources :articles, only: %i[index]
    end
  end
  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :bigint           not null, primary key
#  email                   :string           default(""), not null
#  encrypted_password      :string           default(""), not null
#  reset_password_token    :string
#  reset_password_sent_at  :datetime
#  remember_created_at     :datetime
#  activity_prefecture_ids :string           default([]), is an Array
#  avatar                  :string
#  birthday                :date
#  gender                  :integer
#  name                    :string
#  introduction            :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one関連付けに伴って自動的に用意されるメソッドを呼び出し、PrivacySettingとNotificationSettingを作成
  after_create_commit :create_privacy_setting
  after_create_commit :create_notification_setting
  after_create_commit :create_article_notification_condition

  has_one :privacy_setting, dependent: :destroy
  has_one :notification_setting, dependent: :destroy
  has_one :article_notification_condition, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :conversations, -> (user) { unscope(where: :user_id).where("sender_id = ? OR receiver_id = ?", user.id, user.id) }, dependent: :destroy

  enum gender: { male: 0, female: 1 }

  MAXIMUM_NAME_LENGTH = 30
  validates :name, presence: true, length: { maximum: MAXIMUM_NAME_LENGTH }
  MAXIMUM_INTRODUCTION_LENGTH = 1_000
  validates :introduction, length: { maximum: MAXIMUM_INTRODUCTION_LENGTH }
  validates :birthday, presence: true
  validates :gender, presence: true, inclusion: { in: genders.keys }
  validates :activity_prefecture_ids, presence: true, prefecture_ids: true

  def activity_prefecture_names_ja
    activity_prefecture_ids.map { |p_id| JpPrefecture::Prefecture.find(code: p_id).name }.join("、")
  end

  def age
    return "年齢不明" if birthday.nil?
    Happybirthday.born_on(birthday).age.years_old
  end

  def owner?(current_user)
    return false if current_user.nil?
    id == current_user.id
  end
end

app/controllers/account_settings/profiles_controller.rb
class AccountSettings::ProfilesController < AccountSettings::BaseController
  def edit
  end

  def update
  end
end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @articles = @user.articles.page(params[:page])
  end
end

app/controllers/users/profiles_controller.rb
class Users::ProfilesController < ApplicationController
  # GET /users/1/profiles
  # GET /users/1/profiles.json
  def show
    @user = User.find(params[:user_id])
    @conversation = Conversation.find_or_initialize_by(sender_id: current_user&.id, receiver_id: @user.id)
    @conversation.messages.build
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.page(params[:page])
  end
end

app/helpers/account_settings/profiles_helper.rb
module AccountSettings::ProfilesHelper
end

app/helpers/users/articles_helper.rb
module Users::ArticlesHelper
end

app/helpers/users/profiles_helper.rb
module Users::ProfilesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profiles/show.html.haml
- breadcrumb :user, @user

.l-heading.col-12
  .container
    %h1.u-font-size-big.font-weight-bold.mb-0.d-flex.align-items-center
      = image_tag(@user.avatar.url, alt: "ユーザープロフィール画像", class: "u-image-size-small rounded-circle mr-2")
      = @user.name

.c-tab
  .c-tab__nav
    .c-tab__link.c-tab__link--is-active.col-6
      %i.fas.fa-user.mr-1<>
      プロフィール
    = link_to user_articles_path(@user), class: "c-tab__link col-6" do
      %i.fas.fa-newspaper.mr-1<>
      募集

.c-content-column.col-12
  .c-content-column__label
    %i.fas.fa-quote-right<>
    自己紹介文
  .c-content-column__value
    = simple_format @user.introduction&.html_safe

.c-content-column.col-12
  .c-content-column__label
    %i.fas.fa-map-marker-alt<>
    活動都道府県
  .c-content-column__value
    = @user.activity_prefecture_names_ja

.c-content-column.col-12
  .c-content-column__label
    %i.fas.fa-venus-mars<>
    性別
  .c-content-column__value
    = @user.gender_with_icon

.c-content-column.col-12
  .c-content-column__label
    %i.fas.fa-birthday-cake<>
    年齢
  .c-content-column__value
    = "#{@user.age}歳"

= render 'conversations/form', conversation: @conversation, user: @user