config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'statics#top'

  resource :account_settings, only: %i[show] do
    scope module: 'account_settings' do
      resource :article_notification_conditions, only: %i[edit update]
      resource :emails, only: %i[edit update]
      resource :passwords, only: %i[edit update]
      resource :profiles, only: %i[edit update]
      resource :privacies, only: %i[edit update]
      resource :notifications, only: %i[edit update]
    end
  end
  resources :articles
  resources :helps, only: %i[index]
  resources :improvement_requests, only: %i[new create]
  resources :inquiries, only: %i[new create]
  resources :privacy_policies, only: %i[index]
  resources :statics, only: %i[] do
    collection do
      get :top
    end
  end
  resources :terms, only: %i[index]
  resources :users, only: %i[index] do
    scope module: 'users' do
      get '/', to: 'profiles#show'
      resource :profile, only: %i[show]
      resources :articles, only: %i[index]
    end
  end
  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id             :bigint           not null, primary key
#  user_id        :bigint
#  title          :string
#  body           :text
#  prefecture_ids :string           default([]), is an Array
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Article < ApplicationRecord
  belongs_to :user

  def owner?(_user)
    return false if _user.nil?
    user_id == _user.id
  end

  def prefecture_names_ja
    prefecture_ids.map { |p_id| JpPrefecture::Prefecture.find(code: p_id).name }.join("、")
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = @search_article.result.page(params[:page])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @conversation = Conversation.find_or_initialize_by(sender_id: current_user&.id, receiver_id: @article.user_id)
    @conversation.messages.build
  end

  # GET /articles/new
  def new
    @article = current_user.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      _article_params = params.require(:article).permit(:title, :body, prefecture_ids: [])
    end
end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @articles = @user.articles.page(params[:page])
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users/articles_helper.rb
module Users::ArticlesHelper
end

app/views/articles/_article.html.haml
.row
  = link_to article, class: "c-content-list__item col-12 p-3" do
    %object
      = link_to user_profile_path(article.user), class: "c-content-list__item__header u-font-size-ext-small d-flex align-items-center" do
        = image_tag(article.user.avatar.url, class: "u-image-size-thumbnail rounded-circle mr-1")
        %span.mr-3
          = article.user.name
        %span.text-muted
          = article.created_at.strftime("%Y/%m/%d %H:%M")
    .c-content-list__item__title.text-break
      = article.title
    .c-content-list__item__meta
      %i.fas.fa-map-marker-alt<>
      = article.prefecture_names_ja

app/views/articles/_form.html.haml
.col-12.pt-3
  = form_with(model: @article) do |f|
    - if @article.errors.any?
      #error_explanation
        %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
        %ul
          - @article.errors.full_messages.each do |message|
            %li= message

    .form-group
      = f.label :title
      = f.text_field :title, placeholder: "例）初心者同士で腕を磨きませんか？", class: "form-control"
    .form-group
      = f.label :body
      = f.text_area :body, rows: 5, placeholder: "例）初心者です！\n一緒にビリヤードの練習をできる友達を探しています！\n\nよろしくお願いいたします！", class: "form-control"
    .form-group
      = f.label :prefecture_ids
      = f.collection_select :prefecture_ids, JpPrefecture::Prefecture.all, :code, :name, { include_blank: "選択してください（複数可）", include_hidden: false }, class: "form-control", multiple: true

    = button_tag type: "submit", class: "c-btn c-btn--primary c-btn--block mt-3" do
      %i.fas.fa-pen<>
      募集記事作成

app/views/articles/edit.html.haml
- breadcrumb :edit_article, @article

= render 'common_partials/heading' do
  %i.fas.fa-edit.l-heading__icon<>
  募集記事編集

= render 'form'

app/views/articles/index.html.haml
- breadcrumb :articles

= render 'common_partials/heading' do
  %i.fas.fa-user-friends.l-heading__icon<>
  募集一覧

.p-article-list.col-12
  = render @articles

= paginate(@articles)

app/views/articles/new.html.haml
- breadcrumb :new_article

= render 'common_partials/heading' do
  %i.fas.fa-pen.l-heading__icon<>
  募集記事作成

= render 'form'

app/views/articles/show.html.haml
- breadcrumb :article, @article

.l-heading.col-12
  .container.u-font-size-small.d-flex.align-items-center.mb-2
    = link_to root_path do
      = image_tag(@article.user.avatar.url, class: "u-image-size-thumbnail rounded-circle mr-1")
      %span.mr-3= @article.user.name
    %span.text-muted.u-font-size-ext-small= @article.created_at.strftime("%Y/%m/%d %H:%M")
  .container
    %h1.u-font-size-regular.font-weight-bold.mb-0= @article.title

.c-content-column.col-12
  .c-content-column__label
    %i.fas.fa-quote-right<>
    募集内容
  .c-content-column__value
    = @article.body.html_safe

.c-content-column.col-12
  .c-content-column__label
    %i.fas.fa-map-marker-alt<>
    都道府県
  .c-content-column__value
    = @article.prefecture_names_ja


.c-content-column.col-12
  .c-content-column__label
    %i.fas.fa-user-alt<>
    投稿者
  = link_to user_path(@article.user), class: "c-content-column__value d-flex align-items-center" do
    = image_tag(@article.user.avatar.url, class: "mr-1")
    = @article.user.name

= render 'conversations/form', conversation: @conversation, user: @article.user