config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'statics#top'

  resource :account_settings, only: %i[show] do
    scope module: 'account_settings' do
      resource :article_notification_conditions, only: %i[edit update]
      resource :emails, only: %i[edit update]
      resource :passwords, only: %i[edit update]
      resource :profiles, only: %i[edit update]
      resource :privacies, only: %i[edit update]
      resource :notifications, only: %i[edit update]
    end
  end
  resources :articles
  resources :helps, only: %i[index]
  resources :improvement_requests, only: %i[new create]
  resources :inquiries, only: %i[new create]
  resources :privacy_policies, only: %i[index]
  resources :statics, only: %i[] do
    collection do
      get :top
    end
  end
  resources :terms, only: %i[index]
  resources :users, only: %i[index] do
    scope module: 'users' do
      get '/', to: 'profiles#show'
      resource :profile, only: %i[show]
      resources :articles, only: %i[index]
    end
  end
  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end
end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id          :bigint           not null, primary key
#  sender_id   :integer
#  receiver_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy
  accepts_nested_attributes_for :messages

  validates :sender_id, uniqueness: { scope: :receiver_id, message: "既にトークが存在しています。" }

  scope :between, -> (sender_id, receiver_id) {
    where(sender_id: sender_id, receiver_id: receiver_id)
  }
  scope :participating, -> (user_id) {
    where(sender_id: user_id).or(self.where(receiver_id: user_id))
  }

  def partner(current_user)
    sender_id == current_user.id ? receiver : sender
  end

  def has_any_unread_message?(current_user)
    messages.unread(partner(current_user)).present?
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.participating(current_user.id).page(params[:page])
  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to conversation_messages_path(@conversation), notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: conversation_messages_path(@conversation) }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def conversation_params
    _params = {}
    _params = params.require(:conversation).permit(:receiver_id, messages_attributes: [:body])
    # sender_idに関しては、フォームを経由して受け渡すと、成りすますことができてしまうので、current_userを裏側でセットしている
    _params.merge!(sender_id: current_user.id)
    _params["messages_attributes"]["0"].merge!(user_id: current_user.id)
    _params
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
.row
  = link_to conversation_messages_path(conversation), class: "c-conversation-list__item #{'c-conversation-list__item--has-unread-message' if conversation.has_any_unread_message?(current_user)} d-flex col-12 p-3" do
    - partner = conversation.partner(current_user)
    = image_tag(partner.avatar.url, alt: "プロフィール画像", class: "c-conversation-list__item-avatar mr-3")
    .d-flex.flex-column.align-content-center.w-100
      .d-flex.justify-content-between.mb-1
        .u-font-size-regular= partner.name
        .u-font-size-ext-small.text-muted= conversation.messages.last.received_at
      .d-body.u-font-size-small
        = conversation.messages.last.body.first(20)

app/views/conversations/_form.html.haml
- if user_signed_in?
  - unless user.owner?(current_user)
    - if conversation.new_record?
      .col-12
        = form_with(model: conversation, url: conversations_path, method: :post) do |form|
          = form.hidden_field :receiver_id, value: user.id
          = form.fields_for :messages do |message_form|
            .form-group.mt-5
              = message_form.label :body, "メッセージ"
              = message_form.text_area :body, class: "form-control", rows: 5, placeholder: "#{user.name}様にメッセージを送って、友達になりましょう！"
          %button{type: "submit", class: "c-btn c-btn--primary c-btn--block mt-1"}
            %i.fas.fa-paper-plane
            メッセージを送る
    - else
      .col-12.mt-5
        .text-center.text-muted
          = "#{user.name}様とのトークは既に存在しています。"
        = link_to "トークを開く", conversation_messages_path(conversation), class: "c-btn c-btn--primary c-btn--block mt-1"
- else
  .col-12.mt-5
    .text-center.text-muted
      メッセージを送信するには、<br>ログイン・会員登録が必要です。
      = link_to "会員登録", new_user_registration_path, class: "c-btn c-btn--primary c-btn--block mt-1"
      = link_to "ログイン", new_user_session_path, class: "c-btn c-btn--outline c-btn--primary c-btn--block mt-1"

app/views/conversations/index.html.haml
- breadcrumb :conversations

= render 'common_partials/heading' do
  %i.fas.fa-envelope.l-heading__icon<>
  メッセージ一覧

.p-conversation-list.col-12
  = render @conversations

= paginate(@conversations)