config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'statics#top'

  resource :account_settings, only: %i[show] do
    scope module: 'account_settings' do
      resource :article_notification_conditions, only: %i[edit update]
      resource :emails, only: %i[edit update]
      resource :passwords, only: %i[edit update]
      resource :profiles, only: %i[edit update]
      resource :privacies, only: %i[edit update]
      resource :notifications, only: %i[edit update]
    end
  end
  resources :articles
  resources :helps, only: %i[index]
  resources :improvement_requests, only: %i[new create]
  resources :inquiries, only: %i[new create]
  resources :privacy_policies, only: %i[index]
  resources :statics, only: %i[] do
    collection do
      get :top
    end
  end
  resources :terms, only: %i[index]
  resources :users, only: %i[index] do
    scope module: 'users' do
      get '/', to: 'profiles#show'
      resource :profile, only: %i[show]
      resources :articles, only: %i[index]
    end
  end
  resources :conversations, only: %i[index create] do
    resources :messages, only: %i[index create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# == Schema Information
#
# Table name: articles
#
#  id             :bigint           not null, primary key
#  user_id        :bigint
#  title          :string
#  body           :text
#  prefecture_ids :string           default([]), is an Array
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#

class Article < ApplicationRecord
  belongs_to :user

  def owner?(_user)
    return false if _user.nil?
    user_id == _user.id
  end

  def prefecture_names_ja
    prefecture_ids.map { |p_id| JpPrefecture::Prefecture.find(code: p_id).name }.join("、")
  end


end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id          :bigint           not null, primary key
#  sender_id   :integer
#  receiver_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Conversation < ApplicationRecord
  belongs_to :sender, class_name: "User", foreign_key: "sender_id"
  belongs_to :receiver, class_name: "User", foreign_key: "receiver_id"
  has_many :messages, dependent: :destroy
  accepts_nested_attributes_for :messages

  validates :sender_id, uniqueness: { scope: :receiver_id, message: "既にトークが存在しています。" }

  scope :between, -> (sender_id, receiver_id) {
    where(sender_id: sender_id, receiver_id: receiver_id)
  }
  scope :participating, -> (user_id) {
    where(sender_id: user_id).or(self.where(receiver_id: user_id))
  }

  def partner(current_user)
    sender_id == current_user.id ? receiver : sender
  end

  def has_any_unread_message?(current_user)
    messages.unread(partner(current_user)).present?
  end
end

app/models/improvement_request.rb
# == Schema Information
#
# Table name: improvement_requests
#
#  id           :bigint           not null, primary key
#  user_id      :bigint
#  request_type :integer
#  body         :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class ImprovementRequest < ApplicationRecord
  belongs_to :user, optional: true

  enum request_type: { improvement: 0, addition: 1, bug_fix: 2 }
end

app/models/inquiry.rb
# == Schema Information
#
# Table name: inquiries
#
#  id          :bigint           not null, primary key
#  user_id     :bigint
#  reply_email :string
#  body        :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Inquiry < ApplicationRecord
  belongs_to :user

  validates :reply_email, presence: true
  validates :body, presence: true
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id              :bigint           not null, primary key
#  body            :text
#  conversation_id :bigint
#  user_id         :bigint
#  read            :boolean          default(FALSE)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user

  validates :body, presence: true
  # validates :conversation_id, presence: true
  validates :user_id, presence: true

  scope :unread, -> (partner) { where(user_id: partner.id, read: false) }

  def mine?(current_user)
    user_id == current_user.id
  end
end

app/models/notification_setting.rb
# == Schema Information
#
# Table name: notification_settings
#
#  id                                    :bigint           not null, primary key
#  user_id                               :bigint
#  receive_article_arrival_notifications :boolean          default(TRUE)
#  receive_message_notifications         :boolean          default(TRUE)
#  created_at                            :datetime         not null
#  updated_at                            :datetime         not null
#

class NotificationSetting < ApplicationRecord
  belongs_to :user
end

app/models/privacy_setting.rb
# == Schema Information
#
# Table name: privacy_settings
#
#  id                       :bigint           not null, primary key
#  user_id                  :bigint
#  show_activity_prefecture :boolean          default(TRUE)
#  show_gender              :boolean          default(TRUE)
#  show_age                 :boolean          default(TRUE)
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#

class PrivacySetting < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                      :bigint           not null, primary key
#  email                   :string           default(""), not null
#  encrypted_password      :string           default(""), not null
#  reset_password_token    :string
#  reset_password_sent_at  :datetime
#  remember_created_at     :datetime
#  activity_prefecture_ids :string           default([]), is an Array
#  avatar                  :string
#  birthday                :date
#  gender                  :integer
#  name                    :string
#  introduction            :string
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one関連付けに伴って自動的に用意されるメソッドを呼び出し、PrivacySettingとNotificationSettingを作成
  after_create_commit :create_privacy_setting
  after_create_commit :create_notification_setting
  after_create_commit :create_article_notification_condition

  has_one :privacy_setting, dependent: :destroy
  has_one :notification_setting, dependent: :destroy
  has_one :article_notification_condition, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :conversations, -> (user) { unscope(where: :user_id).where("sender_id = ? OR receiver_id = ?", user.id, user.id) }, dependent: :destroy

  enum gender: { male: 0, female: 1 }

  MAXIMUM_NAME_LENGTH = 30
  validates :name, presence: true, length: { maximum: MAXIMUM_NAME_LENGTH }
  MAXIMUM_INTRODUCTION_LENGTH = 1_000
  validates :introduction, length: { maximum: MAXIMUM_INTRODUCTION_LENGTH }
  validates :birthday, presence: true
  validates :gender, presence: true, inclusion: { in: genders.keys }
  validates :activity_prefecture_ids, presence: true, prefecture_ids: true

  def activity_prefecture_names_ja
    activity_prefecture_ids.map { |p_id| JpPrefecture::Prefecture.find(code: p_id).name }.join("、")
  end

  def age
    return "年齢不明" if birthday.nil?
    Happybirthday.born_on(birthday).age.years_old
  end

  def owner?(current_user)
    return false if current_user.nil?
    id == current_user.id
  end
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  def index
  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.page(params[:page])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_header?
    @show_header == true
  end

  def show_footer?
    @show_footer == true
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/inquiries_helper.rb
module InquiriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common_partials/_heading.html.haml
%h1.l-heading.col-12
  .container.d-flex.align-items-center
    = yield

app/views/common_partials/_modal.html.haml
.c-modal{ id: target_id }
  .c-modal__mask
  .container
    .c-modal__dialog.col-sm-10.col-md-6.mx-auto
      .row
        = yield

app/views/common_partials/_no-content.html.haml
.row
  .col-12.pt-5.px-3.text-center.text-muted
    = yield

app/views/modals/_search.html.haml
= render layout: 'common_partials/modal', locals: { target_id: "search-modal" } do
  .l-heading.col-12
    .container
      %i.fas.fa-search.l-heading__icon<>
      検索

      %i.fas.fa-times.c-modal__close-button
  .c-tab
    .c-tab__nav
      .c-tab__link.col-6{ class: "#{'c-tab__link--is-active' unless controller_name == 'users'}", data: { target: "#tab-search-article-form" } }
        %i.fas.fa-newspaper.mr-1<>
        募集
      .c-tab__link.col-6{ class: "#{'c-tab__link--is-active' if controller_name == 'users'}", data: { target: "#tab-search-user-form" } }
        %i.fas.fa-user-friends.mr-1<>
        ユーザー
    #tab-search-article-form.c-tab__item.container.col-12.py-3{ class: "#{'c-tab__item--is-active' unless controller_name == 'users'}" }
      = search_form_for @search_article, as: :article_q do |form|
        .form-group
          = form.label :title_cont, "募集タイトル"
          = form.text_field :title_cont, placeholder: " ", class: "form-control"
        .form-group
          = form.label :prefecture_ids_in
          = form.collection_select :prefecture_ids_in, JpPrefecture::Prefecture.all, :code, :name, { include_blank: "選択してください（複数可）", include_hidden: false }, class: "form-control", multiple: true
        %button{type: "submit", class: "c-btn c-btn--primary c-btn--block"}
          %i.fas.fa-search<>
          検索
        - if params[:article_q].present?
          = link_to articles_path, class: "c-btn c-btn--gray c-btn--block mt-2" do
            %i.fas.fa-times.text-muted<>
            検索条件をリセット
    #tab-search-user-form.c-tab__item.container.col-12.py-3{ class: "#{'c-tab__item--is-active' if controller_name == 'users'}" }
      = search_form_for @search_user, as: :user_q do |form|
        .form-group
          = form.label :name_cont, "ユーザー名"
          = form.text_field :name_cont, placeholder: " ", class: "form-control"
        .form-group
          = form.label :gender_eq
          = form.select :gender_eq, User.genders_i18n.keys.map {|k| [User.genders_i18n[k], k]}, { include_blank: "選択してください" }, class: "form-control"
        -# .form-row
        -#   .form-group.col
        -#     = form.label :age_gteq, "年齢（下限）"
        -#     = form.select :age_gteq, (0..100).to_a, { include_blank: true }, class: "form-control"
        -#   .form-group.col
        -#     = form.label :age_lteq, "年齢（上限）"
        -#     = form.select :age_lteq, (0..100).to_a, { include_blank: true }, class: "form-control"
        %button{type: "submit", class: "c-btn c-btn--primary c-btn--block"}
          %i.fas.fa-search<>
          検索
        - if params[:user_q].present?
          = link_to users_path, class: "c-btn c-btn--gray c-btn--block mt-2" do
            %i.fas.fa-times.text-muted<>
            検索条件をリセット